// src/components/analysisPanel/components/formatAnalysis.ts

// Matches the existing AnalysisResult shape used across the project
export interface AnalysisResult {
    explanation: string;
    bugs: string[];
    optimizations: string[];
    complexity: string;
    testCases: string[];
  }
  
  /**
   * Formats the analysis object into clean, readable plain text.
   * Shared by CopyAnalysis and DownloadAnalysis so formatting
   * stays consistent and is maintained in exactly one place.
   */
  export function formatAnalysis(analysis: AnalysisResult): string {
    const divider = "─".repeat(48);
  
    const formatList = (items: string[]): string =>
      items.length > 0
        ? items.map((item) => `  • ${item}`).join("\n")
        : "  None detected.";
  
    return [
      "╔══════════════════════════════════════════════╗",
      "       CodeLens AI — Analysis Report",
      "╚══════════════════════════════════════════════╝",
      "",
      divider,
      "📝  CODE EXPLANATION",
      divider,
      analysis.explanation || "No explanation available.",
      "",
      divider,
      "🐞  ISSUES FOUND",
      divider,
      formatList(analysis.bugs),
      "",
      divider,
      "⚡  SUGGESTED IMPROVEMENTS",
      divider,
      formatList(analysis.optimizations),
      "",
      divider,
      "📊  COMPLEXITY",
      divider,
      analysis.complexity || "N/A",
      "",
      divider,
      "🧪  TEST CASES",
      divider,
      formatList(analysis.testCases),
      "",
      divider,
      `Generated by CodeLens AI — ${new Date().toLocaleDateString()}`,
      divider,
    ].join("\n");
  }